/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirQualityRouteImport } from './routes/air-quality'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as HourlyRouteImport } from './routes/hourly'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SurfRouteImport } from './routes/surf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirQualityRoute = AirQualityRouteImport.update({
  id: '/air-quality',
  path: '/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const HourlyRoute = HourlyRouteImport.update({
  id: '/hourly',
  path: '/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfRoute = SurfRouteImport.update({
  id: '/surf',
  path: '/surf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/air-quality': typeof AirQualityRoute
  '/compare': typeof CompareRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/radar': typeof RadarRoute
  '/search': typeof SearchRoute
  '/surf': typeof SurfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/air-quality': typeof AirQualityRoute
  '/compare': typeof CompareRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/radar': typeof RadarRoute
  '/search': typeof SearchRoute
  '/surf': typeof SurfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/air-quality': typeof AirQualityRoute
  '/compare': typeof CompareRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/radar': typeof RadarRoute
  '/search': typeof SearchRoute
  '/surf': typeof SurfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/air-quality'
    | '/compare'
    | '/daily'
    | '/hourly'
    | '/radar'
    | '/search'
    | '/surf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/air-quality'
    | '/compare'
    | '/daily'
    | '/hourly'
    | '/radar'
    | '/search'
    | '/surf'
  id:
    | '__root__'
    | '/'
    | '/air-quality'
    | '/compare'
    | '/daily'
    | '/hourly'
    | '/radar'
    | '/search'
    | '/surf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirQualityRoute: typeof AirQualityRoute
  CompareRoute: typeof CompareRoute
  DailyRoute: typeof DailyRoute
  HourlyRoute: typeof HourlyRoute
  RadarRoute: typeof RadarRoute
  SearchRoute: typeof SearchRoute
  SurfRoute: typeof SurfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-quality': {
      id: '/air-quality'
      path: '/air-quality'
      fullPath: '/air-quality'
      preLoaderRoute: typeof AirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hourly': {
      id: '/hourly'
      path: '/hourly'
      fullPath: '/hourly'
      preLoaderRoute: typeof HourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surf': {
      id: '/surf'
      path: '/surf'
      fullPath: '/surf'
      preLoaderRoute: typeof SurfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirQualityRoute: AirQualityRoute,
  CompareRoute: CompareRoute,
  DailyRoute: DailyRoute,
  HourlyRoute: HourlyRoute,
  RadarRoute: RadarRoute,
  SearchRoute: SearchRoute,
  SurfRoute: SurfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
